name: trz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: 2.2.2
  google_maps_flutter: 1.0.6
  qrscan: 0.2.17
  qr_flutter: 3.2.0
  shared_preferences: 0.5.12+4
  geolocator: 6.1.6
  validators: 2.0.1
  # animations: 1.1.2
  json_annotation: 3.1.0
  mobx: 1.2.1+4
  flutter_mobx: 1.1.0+2
  mobx_codegen: 1.1.2
  provider: 4.3.2+2
  get_it: 5.0.1
  connectivity: 2.0.1
  flushbar: 1.10.4
  permission_handler: 5.0.1+1
  cupertino_icons: 1.0.0
  flutter:
    sdk: flutter
  dio:
    git:
      url: https://github.com/tehort/dio/
      path: dio
  dio_retry: 
    git:
      url: https://github.com/tehort/dio_retry
      path: dio_retry

dev_dependencies:
  build_runner: 1.10.4
  pedantic: 1.9.2
  flutter_launcher_icons: 0.8.1
  json_serializable: 3.5.0
  flutter_native_splash: 0.1.9

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_native_splash:
  image: assets/splash_background.png
  color: "0162b4"

flutter_icons:
  image_path_android: "assets/ic_launcher_round.png"
  image_path_ios: "assets/ic_launcher.png"
  android: true
  ios: true